// <auto-generated />
using Demo.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoApi_TypeGen_NSwag_Starter.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251214154932_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demo.Api.Data.Entities.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("AddressId");

                    b.HasIndex("StudentId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            City = "New York",
                            Country = "USA",
                            PostalCode = "10001",
                            Province = "NY",
                            Street = "123 Main St",
                            StudentId = 1
                        },
                        new
                        {
                            AddressId = 2,
                            City = "Boston",
                            Country = "USA",
                            PostalCode = "02101",
                            Province = "MA",
                            Street = "456 Oak Ave",
                            StudentId = 1
                        },
                        new
                        {
                            AddressId = 3,
                            City = "Chicago",
                            Country = "USA",
                            PostalCode = "60601",
                            Province = "IL",
                            Street = "789 Pine Rd",
                            StudentId = 2
                        },
                        new
                        {
                            AddressId = 4,
                            City = "Seattle",
                            Country = "USA",
                            PostalCode = "98101",
                            Province = "WA",
                            Street = "321 Elm Dr",
                            StudentId = 2
                        },
                        new
                        {
                            AddressId = 5,
                            City = "Austin",
                            Country = "USA",
                            PostalCode = "73301",
                            Province = "TX",
                            Street = "654 Maple Ln",
                            StudentId = 3
                        },
                        new
                        {
                            AddressId = 6,
                            City = "Denver",
                            Country = "USA",
                            PostalCode = "80201",
                            Province = "CO",
                            Street = "987 Cedar Blvd",
                            StudentId = 3
                        },
                        new
                        {
                            AddressId = 7,
                            City = "Portland",
                            Country = "USA",
                            PostalCode = "97201",
                            Province = "OR",
                            Street = "147 Birch St",
                            StudentId = 4
                        },
                        new
                        {
                            AddressId = 8,
                            City = "Miami",
                            Country = "USA",
                            PostalCode = "33101",
                            Province = "FL",
                            Street = "258 Willow Way",
                            StudentId = 4
                        },
                        new
                        {
                            AddressId = 9,
                            City = "Phoenix",
                            Country = "USA",
                            PostalCode = "85001",
                            Province = "AZ",
                            Street = "369 Spruce Ct",
                            StudentId = 5
                        },
                        new
                        {
                            AddressId = 10,
                            City = "Atlanta",
                            Country = "USA",
                            PostalCode = "30301",
                            Province = "GA",
                            Street = "741 Ash Pl",
                            StudentId = 5
                        },
                        new
                        {
                            AddressId = 11,
                            City = "Dallas",
                            Country = "USA",
                            PostalCode = "75201",
                            Province = "TX",
                            Street = "852 Cherry Ter",
                            StudentId = 6
                        },
                        new
                        {
                            AddressId = 12,
                            City = "Houston",
                            Country = "USA",
                            PostalCode = "77001",
                            Province = "TX",
                            Street = "963 Walnut Dr",
                            StudentId = 6
                        },
                        new
                        {
                            AddressId = 13,
                            City = "Philadelphia",
                            Country = "USA",
                            PostalCode = "19101",
                            Province = "PA",
                            Street = "159 Poplar Ave",
                            StudentId = 7
                        },
                        new
                        {
                            AddressId = 14,
                            City = "San Diego",
                            Country = "USA",
                            PostalCode = "92101",
                            Province = "CA",
                            Street = "357 Hickory Rd",
                            StudentId = 7
                        },
                        new
                        {
                            AddressId = 15,
                            City = "San Francisco",
                            Country = "USA",
                            PostalCode = "94101",
                            Province = "CA",
                            Street = "486 Sycamore St",
                            StudentId = 8
                        },
                        new
                        {
                            AddressId = 16,
                            City = "Las Vegas",
                            Country = "USA",
                            PostalCode = "89101",
                            Province = "NV",
                            Street = "624 Magnolia Ln",
                            StudentId = 8
                        },
                        new
                        {
                            AddressId = 17,
                            City = "Detroit",
                            Country = "USA",
                            PostalCode = "48201",
                            Province = "MI",
                            Street = "735 Redwood Blvd",
                            StudentId = 9
                        },
                        new
                        {
                            AddressId = 18,
                            City = "Minneapolis",
                            Country = "USA",
                            PostalCode = "55401",
                            Province = "MN",
                            Street = "846 Cypress Way",
                            StudentId = 9
                        },
                        new
                        {
                            AddressId = 19,
                            City = "Tampa",
                            Country = "USA",
                            PostalCode = "33601",
                            Province = "FL",
                            Street = "957 Dogwood Ct",
                            StudentId = 10
                        },
                        new
                        {
                            AddressId = 20,
                            City = "Baltimore",
                            Country = "USA",
                            PostalCode = "21201",
                            Province = "MD",
                            Street = "168 Beech Pl",
                            StudentId = 10
                        });
                });

            modelBuilder.Entity("Demo.Api.Data.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StudentNo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("StudentId");

                    b.HasIndex("StudentNo")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Active = true,
                            Name = "Alice Johnson",
                            StudentNo = "S0001001"
                        },
                        new
                        {
                            StudentId = 2,
                            Active = true,
                            Name = "Bob Smith",
                            StudentNo = "S0001002"
                        },
                        new
                        {
                            StudentId = 3,
                            Active = false,
                            Name = "Charlie Brown",
                            StudentNo = "S0001003"
                        },
                        new
                        {
                            StudentId = 4,
                            Active = true,
                            Name = "Diana Prince",
                            StudentNo = "S0001004"
                        },
                        new
                        {
                            StudentId = 5,
                            Active = true,
                            Name = "Edward Norton",
                            StudentNo = "S0001005"
                        },
                        new
                        {
                            StudentId = 6,
                            Active = false,
                            Name = "Fiona Davis",
                            StudentNo = "S0001006"
                        },
                        new
                        {
                            StudentId = 7,
                            Active = true,
                            Name = "George Wilson",
                            StudentNo = "S0001007"
                        },
                        new
                        {
                            StudentId = 8,
                            Active = true,
                            Name = "Hannah Moore",
                            StudentNo = "S0001008"
                        },
                        new
                        {
                            StudentId = 9,
                            Active = true,
                            Name = "Ivan Taylor",
                            StudentNo = "S0001009"
                        },
                        new
                        {
                            StudentId = 10,
                            Active = false,
                            Name = "Julia Anderson",
                            StudentNo = "S0001010"
                        });
                });

            modelBuilder.Entity("Demo.Api.Data.Entities.Address", b =>
                {
                    b.HasOne("Demo.Api.Data.Entities.Student", "Student")
                        .WithMany("Addresses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Demo.Api.Data.Entities.Student", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
